// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paperbunkr.Data;

#nullable disable

namespace Paperbunkr.Data.Migrations
{
    [DbContext(typeof(PaperbunkrDbContext))]
    partial class PaperbunkrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CategorySeries", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("CategorySeries");
                });

            modelBuilder.Entity("ContinuitySeries", b =>
                {
                    b.Property<int>("ContinuitiesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ContinuitiesId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("ContinuitySeries");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveSkinKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("default");

                    b.Property<bool>("AutoNavigateComics")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("WhiteSmoke");

                    b.Property<string>("BackupLocation")
                        .HasColumnType("TEXT");

                    b.Property<int>("BackupsToKeep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5);

                    b.Property<bool>("DefaultAutoRotate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<double>("DefaultBrightness")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("DefaultContrast")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<double>("DefaultGamma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<string>("DefaultPageFitMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("FitWidth");

                    b.Property<string>("DefaultPageLayoutMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Single");

                    b.Property<double>("DefaultSaturation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.0);

                    b.Property<bool>("HighQualityPageDisplay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("ImageBackgroundMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Color");

                    b.Property<int?>("LibraryActiveCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryActiveContentType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LibraryDetailsColumns")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LibraryFilterMissingIssues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("LibraryFilterTrackedOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("LibraryFilterUnreadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LibraryGranularity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Issue");

                    b.Property<double>("LibraryGridDensity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.0);

                    b.Property<string>("LibraryGroupField")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<string>("LibraryIssueListGroupField")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<string>("LibraryIssueListSortDirection")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Descending");

                    b.Property<string>("LibraryIssueListSortField")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Added");

                    b.Property<string>("LibrarySearchMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("All");

                    b.Property<string>("LibrarySearchQuery")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LibraryShowContinueReadingButton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("LibraryShowLanguageBadge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("LibraryShowPublisherBadge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("LibraryShowTileTitles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("LibraryShowUnreadBadge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LibrarySortDirection")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Descending");

                    b.Property<string>("LibrarySortField")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("DateAdded");

                    b.Property<bool>("LibraryUseLanguageIcon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LibraryViewMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("PosterGrid");

                    b.Property<double>("MagnifierOpacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.0);

                    b.Property<int>("MagnifierSizePixels")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(200);

                    b.Property<double>("MagnifierZoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2.0);

                    b.Property<string>("MetadataResolutionPolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Automatic");

                    b.Property<bool>("MinimizeToTray")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MinimizeToTrayNoticeShown")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MouseWheelSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2.0);

                    b.Property<bool>("NavRailPinned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OpenLastPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PageMarginEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<double>("PageMarginPercentWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.050000000000000003);

                    b.Property<int>("PageTransitionDurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(250);

                    b.Property<string>("PageTransitionStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<bool>("PreferNativeOpenGl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("ReducedMotion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenderingBackend")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Auto");

                    b.Property<bool>("ResetZoomOnPageChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("ReverseRtlNavigation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("SelectedFontFamily")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowScrubberOverlay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BookSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastChapterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastCharacterOffset")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastOpenedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookSeriesId");

                    b.HasIndex("FilePath");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.BookBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterOffset")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("BookBookmarks");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.BookFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("BookFolders");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.BookSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("BookSeries");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.Continuity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Continuities");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.EventMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("StoryEventId");

                    b.ToTable("EventMemberships");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ExternalMediaId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("ExternalMediaIds");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ExternalMetadataSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("ExternalMetadataSnapshots");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ExternalRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Scale")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("ExternalRatings");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AddedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternateNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternateSeries")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AutoRotateOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookAge")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookCollectionStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookCondition")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookOwner")
                        .HasColumnType("TEXT");

                    b.Property<float?>("BookPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("BookStore")
                        .HasColumnType("TEXT");

                    b.Property<float?>("BrightnessOverride")
                        .HasColumnType("REAL");

                    b.Property<string>("Characters")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Checked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unknown");

                    b.Property<string>("Colorist")
                        .HasColumnType("TEXT");

                    b.Property<float?>("CommunityRating")
                        .HasColumnType("REAL");

                    b.Property<float?>("ContrastOverride")
                        .HasColumnType("REAL");

                    b.Property<int?>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverArtist")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomThumbnailKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Editor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FileCreationTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FileIsMissing")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FileModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .HasColumnType("TEXT");

                    b.Property<float?>("GammaOverride")
                        .HasColumnType("REAL");

                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inker")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinalIssue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlaceholder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageISO")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastPageRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Letterer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locations")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainCharacterOrTeam")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MissingAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NewPages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT");

                    b.Property<int>("OpenCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OpenedTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageFitModeOverride")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageLayoutModeOverride")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Penciller")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("ReadingModeOverride")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleasedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Review")
                        .HasColumnType("TEXT");

                    b.Property<float?>("SaturationOverride")
                        .HasColumnType("REAL");

                    b.Property<string>("ScanInformation")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriesGroup")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoryArc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoryArcNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Teams")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Translator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Volume")
                        .HasColumnType("TEXT");

                    b.Property<string>("Web")
                        .HasColumnType("TEXT");

                    b.Property<string>("Writer")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FilePath");

                    b.HasIndex("SeriesId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.IssueBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueBookmarks");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.IssueCustomValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId", "Name");

                    b.ToTable("IssueCustomValues");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.IssuePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("RotationDegrees")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IssueId", "PageNumber")
                        .IsUnique();

                    b.ToTable("IssuePages");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.IssueTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueTags");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.KeyBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandId")
                        .IsUnique();

                    b.ToTable("KeyBindings");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.MediaRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceSeriesId");

                    b.HasIndex("TargetSeriesId");

                    b.ToTable("MediaRelations");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.MetadataProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProposedValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Status");

                    b.ToTable("MetadataProposals");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.PluginCommandState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommandKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PluginKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PluginCommandStates");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ProviderCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProviderCredentials");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ReadingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArcId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArcName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc));

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StoryEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("User");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc));

                    b.HasKey("Id");

                    b.HasIndex("StoryEventId");

                    b.ToTable("ReadingLists");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ReadingListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadingListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("ReadingListId");

                    b.ToTable("ReadingListItems");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ReadingListTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadingListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReadingListId");

                    b.ToTable("ReadingListTags");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.RelationEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaRelationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderRelationType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaRelationId");

                    b.ToTable("RelationEvidence");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CoverIssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PageLayoutMode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unknown");

                    b.Property<string>("SortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unknown");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoverIssueId");

                    b.HasIndex("Name");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.SeriesConflict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExistingSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncomingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesAId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeriesBId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Similarity")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExistingSeriesId");

                    b.HasIndex("SeriesAId");

                    b.HasIndex("SeriesBId");

                    b.HasIndex("Status");

                    b.ToTable("SeriesConflicts");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.SeriesTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("SeriesTitles");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.SmartList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SmartLists");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.SmartListCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomValueName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SmartListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value2")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VirtualTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SmartListId");

                    b.ToTable("SmartListConditions");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.StoryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("StoryEvents");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.TrackingLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncedIssueNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId", "Service", "ExternalId")
                        .IsUnique();

                    b.ToTable("TrackingLinks");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.VirtualTagDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaptionFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VirtualTagDefinitions");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.WatchedFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Watch")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("WatchedFolders");
                });

            modelBuilder.Entity("CategorySeries", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paperbunkr.Data.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContinuitySeries", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Continuity", null)
                        .WithMany()
                        .HasForeignKey("ContinuitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paperbunkr.Data.Entities.Series", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.Book", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.BookSeries", "BookSeries")
                        .WithMany("Books")
                        .HasForeignKey("BookSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BookSeries");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.BookBookmark", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Book", "Book")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.EventMembership", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paperbunkr.Data.Entities.StoryEvent", "StoryEvent")
                        .WithMany("Members")
                        .HasForeignKey("StoryEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("StoryEvent");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ExternalMediaId", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ExternalMetadataSnapshot", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ExternalRating", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.Issue", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Series", "Series")
                        .WithMany("Issues")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.IssueBookmark", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Issue", "Issue")
                        .WithMany("Bookmarks")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.IssueCustomValue", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Issue", "Issue")
                        .WithMany("CustomValues")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.IssuePage", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.IssueTag", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Issue", "Issue")
                        .WithMany("Tags")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.MediaRelation", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Series", "SourceSeries")
                        .WithMany()
                        .HasForeignKey("SourceSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Paperbunkr.Data.Entities.Series", "TargetSeries")
                        .WithMany()
                        .HasForeignKey("TargetSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceSeries");

                    b.Navigation("TargetSeries");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.MetadataProposal", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Issue", "Issue")
                        .WithMany("MetadataProposals")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Paperbunkr.Data.Entities.Series", "Series")
                        .WithMany("MetadataProposals")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Issue");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ReadingList", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.StoryEvent", "StoryEvent")
                        .WithMany()
                        .HasForeignKey("StoryEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StoryEvent");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ReadingListItem", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Paperbunkr.Data.Entities.ReadingList", "ReadingList")
                        .WithMany("Items")
                        .HasForeignKey("ReadingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("ReadingList");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ReadingListTag", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.ReadingList", "ReadingList")
                        .WithMany("Tags")
                        .HasForeignKey("ReadingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingList");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.RelationEvidence", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.MediaRelation", "MediaRelation")
                        .WithMany("Evidence")
                        .HasForeignKey("MediaRelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaRelation");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.Series", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Issue", "CoverIssue")
                        .WithMany()
                        .HasForeignKey("CoverIssueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CoverIssue");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.SeriesConflict", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Series", "ExistingSeries")
                        .WithMany()
                        .HasForeignKey("ExistingSeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Paperbunkr.Data.Entities.Series", "SeriesA")
                        .WithMany()
                        .HasForeignKey("SeriesAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Paperbunkr.Data.Entities.Series", "SeriesB")
                        .WithMany()
                        .HasForeignKey("SeriesBId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExistingSeries");

                    b.Navigation("SeriesA");

                    b.Navigation("SeriesB");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.SeriesTitle", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Series", "Series")
                        .WithMany("Titles")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.SmartListCondition", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.SmartList", "SmartList")
                        .WithMany("Conditions")
                        .HasForeignKey("SmartListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SmartList");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.TrackingLink", b =>
                {
                    b.HasOne("Paperbunkr.Data.Entities.Series", "Series")
                        .WithMany("TrackingLinks")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.Book", b =>
                {
                    b.Navigation("Bookmarks");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.BookSeries", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.Issue", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("CustomValues");

                    b.Navigation("MetadataProposals");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.MediaRelation", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.ReadingList", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.Series", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("MetadataProposals");

                    b.Navigation("Titles");

                    b.Navigation("TrackingLinks");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.SmartList", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("Paperbunkr.Data.Entities.StoryEvent", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
