using System.Collections.Generic;
using System.Linq;

namespace Paperbunkr.App.Models;

/// <summary>
/// One searchable entry per settings group card (docs/superpowers/specs/
/// 2026-08-28-preferences-rework-design.md "Search"). <see cref="Keywords"/> carries the labels of
/// the individual controls inside the group so a query like "double page" still resolves to the
/// Reader → Display card. <see cref="AnchorKey"/> matches the <c>Tag</c> on that group's
/// <c>Border</c> in the section's .axaml, which the shell scrolls into view. <see cref="SubTab"/> is the key of the section tab
/// that holds the group (docs/superpowers/specs/2026-09-26-preferences-reader-organize-tabs-design.md); the shell selects it
/// before scrolling. Null for sections without tabs (Library Health has its own reveal).
/// </summary>
public sealed record PreferenceIndexEntry(
    PreferencesSection Section,
    string GroupTitle,
    string Title,
    IReadOnlyList<string> Keywords,
    string AnchorKey,
    string? SubTab = null);

/// <summary>
/// The static catalog behind the Preferences search box. Hand-maintained; kept honest by
/// <c>PreferenceIndexTests</c>, which asserts every <see cref="PreferenceIndexEntry.AnchorKey"/>
/// resolves to a real <c>Border.Tag</c> in its section control.
/// </summary>
public static class PreferenceIndex
{
    /// <summary>The entry with this anchor key, or null.</summary>
    public static PreferenceIndexEntry? Find(string? anchorKey)
        => anchorKey is null ? null : Entries.FirstOrDefault(e => e.AnchorKey == anchorKey);

    public static IReadOnlyList<PreferenceIndexEntry> Entries { get; } = new PreferenceIndexEntry[]
    {
        new(PreferencesSection.General, "Startup", "Startup",
            new[] { "startup", "launch", "reopen", "last session", "restore screen", "scan on startup", "rescan folders" },
            "general.startup"),
        new(PreferencesSection.General, "Reading", "Reading",
            new[] { "resume", "left off", "last page", "auto advance", "next issue", "open next", "rate on finish", "quick review", "review prompt" },
            "general.reading"),
        new(PreferencesSection.General, "Library", "Library",
            new[] { "drag and drop", "drag drop", "import files", "drop files" },
            "general.library"),
        new(PreferencesSection.General, "Window", "Window",
            new[] { "minimize", "tray", "close to tray", "system tray" },
            "general.window"),

        new(PreferencesSection.Appearance, "Skins", "Skin",
            new[] { "skin", "theme", "colors", "palette", "windows 11", "evolved amber", "install skin", "crpck", "browse skin", "skins folder" },
            "appearance.skin"),
        new(PreferencesSection.Appearance, "Font", "Font",
            new[] { "font", "typeface", "font family" },
            "appearance.font"),
        new(PreferencesSection.Appearance, "Cover cosmetics", "Cover cosmetics",
            new[] { "binding spine", "spine", "progress ring", "read progress", "ring", "accent glow", "glow", "hover glow", "cover", "poster", "panorama", "selection checkbox", "multi-select", "select", "ctrl click", "reading list", "mosaic", "collage", "splash", "ambient", "dots", "fade in", "thumbnails", "tooltip", "tooltips", "hover card" },
            "appearance.cosmetics"),
        new(PreferencesSection.Appearance, "Detail screens", "Detail screens",
            new[] { "hero backdrop", "backdrop", "blur", "series accent", "accent color", "dominant color", "detail", "cover color" },
            "appearance.detail"),
        new(PreferencesSection.Appearance, "Home", "Home",
            new[] { "home", "sections", "reorder", "hide section", "greeting", "seasonal", "holiday", "recommendations", "not interested", "hidden recommendations", "spotlight" },
            "appearance.home"),
        new(PreferencesSection.Appearance, "Interface", "Interface",
            new[] { "density", "compact", "spacious", "spacing", "row height", "motion", "reduce motion", "animation", "transitions", "nav rail", "hover", "expand", "smooth scrolling", "scroll", "mouse wheel", "developer", "design showcase", "debug" },
            "appearance.interface"),

        new(PreferencesSection.Library, "Comic Library Folders", "Comic Library Folders",
            new[] { "comic folder", "watched folder", "scan", "generate covers", "sync metadata", "watch for changes" },
            "library.comicFolders"),
        new(PreferencesSection.Library, "Book Folders", "Book Folders",
            new[] { "book folder", "novel", "epub", "pdf", "scan books" },
            "library.bookFolders"),
        new(PreferencesSection.Library, "Migrate from ComicRack CE", "Migrate from ComicRack CE",
            new[] { "migrate", "comicrack", "ce", "import library" },
            "library.migration"),
        new(PreferencesSection.Library, "Virtual Tags", "Virtual Tags",
            new[] { "virtual tag", "caption format", "computed tag" },
            "library.virtualTags"),
        new(PreferencesSection.Library, "Library Health", "Library Health",
            new[] { "missing files", "verify", "confirmed missing", "recently removed", "restore", "relink", "dismiss all", "ghost", "library health" },
            "library.health"),
        // One entry per Library Health section (docs/superpowers/specs/2026-09-26-library-health-subtabs-design.md) - opening a hit
        // switches to the section's sub-tab, opens it and scrolls to it. Anchors are the sections' own Border tags.
        new(PreferencesSection.Library, "Library Health", "Duplicate files",
            new[] { "duplicate", "duplicates", "same file", "keep largest", "dismiss all", "merge entries", "copies" },
            "library.healthDuplicates"),
        new(PreferencesSection.Library, "Library Health", "Series conflicts",
            new[] { "series conflict", "conflict", "merge series", "keep separate", "keep all separate", "same series" },
            "library.healthSeriesConflicts"),
        new(PreferencesSection.Library, "Library Health", "Content type",
            new[] { "content type", "unknown content type", "comic or manga", "unknown series" },
            "library.healthContentType"),
        new(PreferencesSection.Library, "Library Health", "Metadata proposals",
            new[] { "metadata proposal", "proposal", "proposals", "accept all", "reject all", "applied automatically", "filename parser", "review metadata",
                    "apply automatically", "auto-apply", "auto apply", "confidence", "confidence threshold", "resolution policy", "prompt" },
            "library.healthProposals"),
        new(PreferencesSection.Library, "Library Health", "Advertisement pages",
            new[] { "advertisement", "advertisement pages", "ad pages", "ads", "ad detection" },
            "library.healthAdPages"),
        new(PreferencesSection.Library, "Library Health", "Reported pages",
            new[] { "reported pages", "bad page", "broken page", "page report" },
            "library.healthReportedPages"),
        new(PreferencesSection.Library, "Library Health", "Find similar series",
            new[] { "similar series", "scan for similar names", "punctuation variant", "split series" },
            "library.healthSimilarSeries"),
        new(PreferencesSection.Library, "Library Health", "Publisher logos",
            new[] { "publisher logos", "publisher icons", "missing publisher", "no publisher", "publisher gaps", "logo", "icons folder", "custom icons" },
            "library.healthPublishers"),
        new(PreferencesSection.Library, "Library Health", "Collection gaps",
            new[] { "collection gaps", "gaps", "missing issues", "missing numbers", "holes", "holes in your collection", "incomplete run", "not a gap" },
            "library.healthCollectionGaps"),
        new(PreferencesSection.Library, "Library Health", "Metadata consistency",
            new[] { "metadata consistency", "consistency", "inconsistent", "wrong year", "year outlier", "publisher mismatch", "age rating mismatch", "outlier", "this is intended" },
            "library.healthMetadataConsistency"),
        new(PreferencesSection.Library, "Library Health", "Missing files",
            new[] { "missing files", "relink", "relink all", "dismiss all", "ghost" },
            "library.healthMissing"),
        new(PreferencesSection.Library, "Library Health", "Empty rows",
            new[] { "empty rows", "empty series", "empty issue", "nothing empty" },
            "library.healthEmptyRows"),
        new(PreferencesSection.Library, "Library Health", "Recently removed",
            new[] { "recently removed", "restore removed", "undo remove" },
            "library.healthRecentlyRemoved"),

        new(PreferencesSection.Automation, "Scheduled Tasks", "Scheduled Tasks",
            new[] { "schedule", "scheduled task", "automation", "automatic", "recurring", "background job", "backup", "scan on startup", "periodic", "cron" },
            "automation.tasks"),

        // Reader: one entry per group, each naming the tab that holds it (PreferencesScreenViewModel.ReaderTabKeys).
        new(PreferencesSection.Reader, "Reading direction", "Reading direction",
            new[] { "right to left", "rtl", "manga", "page turn direction", "reverse" },
            "reader.rtl", "pages"),
        new(PreferencesSection.Reader, "Layout", "Layout",
            new[] { "fit mode", "default fit", "fit width", "fit height", "auto rotate", "rotate landscape", "double page", "spread", "page layout" },
            "reader.layout", "pages"),
        new(PreferencesSection.Reader, "Turning", "Turning pages",
            new[] { "page transition", "transition speed", "crossfade", "slide", "animation", "reset zoom", "skip deleted", "skip advertisement", "skip ads", "pre-open", "next issue", "preload" },
            "reader.turning", "pages"),
        new(PreferencesSection.Reader, "Tap zones", "Tap zones",
            new[] { "tap zone", "click zone", "touch", "layout", "l-shaped", "kindle", "edge", "left handed", "invert", "mouse click", "paged", "continuous" },
            "reader.tapZones", "controls"),
        new(PreferencesSection.Reader, "Mouse & controller", "Mouse & controller",
            new[] { "mouse button", "side button", "back button", "forward button", "gamepad", "controller", "xbox", "clicker", "media keys", "mouse wheel", "scroll speed", "wheel speed" },
            "reader.pointerInput", "controls"),
        new(PreferencesSection.Reader, "Panels & zoom", "Panels & zoom",
            new[] { "guided view", "panel", "panels", "comic panel", "smart zoom", "double click", "double tap", "zoom to panel", "panel by panel", "zoom" },
            "reader.panelsZoom", "controls"),
        new(PreferencesSection.Reader, "Quality", "Page quality",
            new[] { "high quality", "smoother scaling", "scaling", "page display", "cpu" },
            "reader.quality", "image"),
        new(PreferencesSection.Reader, "Image adjustment", "Image adjustment",
            new[] { "brightness", "contrast", "saturation", "gamma", "image adjustment", "auto levels", "auto contrast", "levels", "washed out", "sharpen", "sharpening" },
            "reader.imageAdjust", "image"),
        new(PreferencesSection.Reader, "Auto-crop", "Auto-crop margins",
            new[] { "crop", "auto crop", "trim", "margins", "borders", "white border", "scan border", "black border" },
            "reader.autoCrop", "image"),
        new(PreferencesSection.Reader, "Background & margin", "Background & margin",
            new[] { "canvas background", "background color", "background texture", "texture", "page margin", "margin width" },
            "reader.background", "image"),
        new(PreferencesSection.Reader, "Toolbar", "Toolbar",
            new[] { "toolbar", "auto hide", "hide toolbar", "idle", "chrome", "reveal", "per cluster", "ambient", "controls fade" },
            "reader.toolbar", "comfort"),
        new(PreferencesSection.Reader, "Session", "Reading session",
            new[] { "stats", "hud", "session", "pace", "reading time", "break", "eye", "20-20-20", "reminder", "nudge", "rest" },
            "reader.session", "comfort"),
        new(PreferencesSection.Reader, "Night", "Night tint",
            new[] { "warm", "night", "tint", "blue light", "night light", "warm tint", "evening" },
            "reader.night", "comfort"),
        new(PreferencesSection.Reader, "Info panel", "Info panel",
            new[] { "info panel", "summary", "spoiler", "spoilers", "credits", "characters", "story arc" },
            "reader.infoPanel", "comfort"),
        new(PreferencesSection.Reader, "Profiles", "Reader Profiles",
            new[] { "profile", "reader profile", "preset", "manga night", "webtoon", "tablet", "default profile", "workspace" },
            "reader.profiles", "profiles"),

        new(PreferencesSection.KeyboardShortcuts, "Import / Export", "Import / Export Layout",
            new[] { "import layout", "export layout", "shortcut layout", "keybindings file" },
            "shortcuts.io"),
        new(PreferencesSection.KeyboardShortcuts, "Navigation", "Navigation Shortcuts",
            new[] { "pan", "scroll", "page up", "page down", "home", "end", "next page", "previous page" },
            "shortcuts.navigation"),
        new(PreferencesSection.KeyboardShortcuts, "Zoom & Fit", "Zoom & Fit Shortcuts",
            new[] { "zoom in", "zoom out", "fit width", "fit height", "best fit", "actual size" },
            "shortcuts.zoomFit"),
        new(PreferencesSection.KeyboardShortcuts, "Display", "Display Shortcuts",
            new[] { "fullscreen", "rotate", "rotate clockwise", "rotate counter clockwise" },
            "shortcuts.display"),
        new(PreferencesSection.KeyboardShortcuts, "General", "General Shortcuts",
            new[] { "back", "forward", "navigate back", "navigate forward", "quick open", "undo", "redo", "quit", "escape", "focus search", "sidebar", "mouse button", "thumb button" },
            "shortcuts.general"),
        new(PreferencesSection.KeyboardShortcuts, "Library", "Library Shortcuts",
            new[] { "refresh", "preview panel", "f5" },
            "shortcuts.library"),
        new(PreferencesSection.KeyboardShortcuts, "Gamepad", "Gamepad",
            new[] { "gamepad", "controller", "xbox", "stick", "trigger", "d-pad", "bumper" },
            "shortcuts.gamepad"),
        new(PreferencesSection.KeyboardShortcuts, "Book reader", "Book Reader Shortcuts",
            new[] { "book", "epub", "next page", "previous page", "announce position", "screen reader" },
            "shortcuts.bookReader"),
        new(PreferencesSection.KeyboardShortcuts, "Compare", "Compare Shortcuts",
            new[] { "compare", "flip", "keep a", "keep b", "flicker" },
            "shortcuts.compare"),
        new(PreferencesSection.KeyboardShortcuts, "All screens", "All-Screen Shortcuts",
            new[] { "refresh", "new", "save", "tab", "move", "open", "context menu", "scroll", "controller", "d-pad", "first", "last", "page up", "page down", "rename", "delete" },
            "shortcuts.allScreens"),
        new(PreferencesSection.KeyboardShortcuts, "Books", "Books Shortcuts",
            new[] { "books", "select all", "edit selection", "remove selection" },
            "shortcuts.books"),
        new(PreferencesSection.KeyboardShortcuts, "Detail screens", "Detail Screen Shortcuts",
            new[] { "detail", "continue reading", "edit properties" },
            "shortcuts.detailScreens"),
        new(PreferencesSection.KeyboardShortcuts, "Smart lists", "Smart List Shortcuts",
            new[] { "smart list", "duplicate" },
            "shortcuts.smartLists"),

        new(PreferencesSection.Connections, "Reading List Sources", "Reading List Sources",
            new[] { "comicvine", "api key", "metron", "reading list source", "arc lookup" },
            "connections.metadataSources"),
        new(PreferencesSection.Connections, "Grand Comics Database data", "Series continuity and on-sale dates",
            new[] { "gcd", "grand comics database", "comics.org", "on-sale date", "continuity", "renumbering", "reboot", "download data", "licence", "license" },
            "connections.gcdData"),
        new(PreferencesSection.Connections, "Metron account", "Sync with my Metron account",
            new[] { "metron", "account sync", "pull list", "collection", "wish list", "scrobble", "read dates", "reading history", "import from metron", "sync now" },
            "connections.metronSync"),
        new(PreferencesSection.Connections, "Download automation", "Prowlarr and qBittorrent",
            new[] { "prowlarr", "qbittorrent", "indexer", "torrent", "download client", "api key", "web ui", "acquisition", "mylar", "test connection", "category" },
            "connections.downloadAutomation"),
        new(PreferencesSection.Connections, "Trackers", "Trackers",
            new[] { "tracker", "anilist", "myanimelist", "mal", "shikimori", "bangumi", "mangabaka", "connect", "token" },
            "connections.trackers"),
        new(PreferencesSection.Connections, "Tracking behavior", "Tracking behavior",
            new[] { "tracker", "tracking", "auto sync", "update progress", "mark as read", "after reading", "source metadata", "link panel", "komikku", "content type", "classify", "manhwa", "manhua", "ask before",
                    "completed", "marked completed", "refresh provider data", "series status" },
            "connections.trackingBehavior"),

        new(PreferencesSection.Acquisition, "Connections", "Prowlarr, qBittorrent and ComicVine",
            new[] { "prowlarr", "qbittorrent", "comicvine", "indexer", "api key", "torrent", "download client", "web ui", "password", "acquisition", "test connection" },
            "acquisition.connections"),
        // Organize & Scrape: one entry per group, each naming its tab (OrganizeScrapeSettingsViewModel.TabKeys).
        new(PreferencesSection.OrganizeScrape, "Source", "Scrape source",
            new[] { "scrape from", "source", "provider", "comicvine", "metron", "api key", "login", "connections", "scraper" },
            "organizeScrape.source", "scrape"),
        new(PreferencesSection.OrganizeScrape, "Matching", "Matching",
            new[] { "scrape", "match", "auto choose", "best match", "confirm issue", "search results", "results considered", "series art", "cover thumbnails", "covers", "delay", "review dialog" },
            "organizeScrape.matching", "scrape"),
        new(PreferencesSection.OrganizeScrape, "Writing", "Writing",
            new[] { "overwrite", "blank", "never blank", "fields", "fields to fill in", "credits", "summary", "imprint", "convert imprints", "parent publisher" },
            "organizeScrape.writing", "scrape"),
        new(PreferencesSection.OrganizeScrape, "Ignore rules", "Ignore rules",
            new[] { "filter", "ignore", "ignored publishers", "ignored search words", "volumes before year", "volumes after year", "never ignore", "cluster library manager", "advanced scraper" },
            "organizeScrape.filters", "filters"),
        new(PreferencesSection.OrganizeScrape, "Name mapping", "Name mapping",
            new[] { "imprint", "imprint override", "publisher alias", "alias", "publisher", "parent publisher", "rename publisher" },
            "organizeScrape.names", "filters"),
        new(PreferencesSection.OrganizeScrape, "Organizer profiles", "Organizer profiles",
            new[] { "organize", "organizer", "profile", "move files", "copy files", "rename files", "folder template", "naming template", "undo" },
            "organizeScrape.profiles", "organize"),
        new(PreferencesSection.Acquisition, "Searching", "Searching",
            new[] { "search interval", "check every", "poll", "release size", "minimum size", "maximum size", "release group", "ignored words", "cbz", "cbr", "prefer cbz", "wanted" },
            "acquisition.search"),
        new(PreferencesSection.Acquisition, "Import", "Import",
            new[] { "import", "destination", "library folder", "naming template", "rename", "comicinfo", "tag", "seeding", "remove download", "volumeyear" },
            "acquisition.import"),
        new(PreferencesSection.Acquisition, "Automatic downloads", "Automatic downloads",
            new[] { "auto grab", "automatic", "download automatically", "minimum score", "approve" },
            "acquisition.autograb"),

        new(PreferencesSection.Sharing, "Share this library", "Share this library",
            new[] { "share", "sharing", "server", "host", "network", "lan", "vpn", "password", "port", "certificate", "fingerprint", "remote", "serve", "read-only" },
            "sharing.host"),
        new(PreferencesSection.Sharing, "Remote libraries", "Remote libraries",
            new[] { "remote", "library", "connect", "add", "server", "host", "address", "trust", "fingerprint", "relink", "offline", "sync", "another computer" },
            "sharing.remote"),

        new(PreferencesSection.Advanced, "Rendering", "Rendering",
            new[] { "graphics backend", "gpu", "software renderer", "opengl", "angle", "hardware acceleration" },
            "advanced.rendering"),
        new(PreferencesSection.Advanced, "File Types", "File Types",
            new[] { "file association", "file types", "cbz", "cbr", "cb7", "cbl", "default app", "open with", "thumbnail", "file explorer", "explorer", "cover" },
            "advanced.fileAssociation"),
        new(PreferencesSection.Advanced, "Backup Manager", "Backup Manager",
            new[] { "backup", "restore", "backup location", "backups to keep" },
            "advanced.backup"),

        new(PreferencesSection.About, "Updates", "Updates",
            new[] { "update", "check for updates", "auto update", "version", "new version", "copy version" },
            "about.updates", SubTab: "overview"),
        new(PreferencesSection.About, "Project", "Project",
            new[] { "github", "wiki", "help", "report an issue", "bug", "releases", "logs", "log folder", "data folder", "crash log" },
            "about.project", SubTab: "overview"),
        new(PreferencesSection.About, "Changelog", "Changelog",
            new[] { "changelog", "what's new", "whats new", "release notes", "history" },
            "about.changelog", SubTab: "changelog"),
        new(PreferencesSection.About, "Legal & notices", "Legal & notices",
            new[] { "license", "agpl", "privacy", "terms", "comicvine", "metron", "api key", "open source", "third party", "notices", "credits", "acknowledgements" },
            "about.legal", SubTab: "legal"),
    };
}
