namespace Paperbunkr.Data.Entities;

/// <summary>
/// Comic List screen's sort keys (docs/superpowers/specs/2026-08-18-issue-list-pluggable-sort-
/// group-design.md's original Slice 1, extended by docs/superpowers/specs/
/// 2026-08-18-library-book-centric-redesign-design.md's Slice 1 - the full CE field-coverage table
/// lives there, including what's deliberately excluded as CE bugs/UI-only concepts).
/// </summary>
public enum IssueListSortField
{
    Number,
    Series,
    Title,
    Writer,
    Publisher,
    Genre,
    Format,
    Added,
    Opened,
    Released,
    Year,
    PageCount,
    FileSize,
    Rating,
    CommunityRating,
    ReadPercentage,
    OpenCount,
    Tags,
    Status,
    Volume,
    Penciller,
    Inker,
    Colorist,
    Letterer,
    CoverArtist,
    Editor,
    Translator,
    Characters,
    Teams,
    Locations,
    BookPrice,
    BookAge,
    BookStore,
    BookOwner,
    BookCondition,
    BookCollectionStatus,
    BookLocation,
    ISBN,
    Read,
    Imprint,
    Language,
    AgeRating,
    StoryArc,
    SeriesGroup,
    FilePath,
    FileName,
    FileDirectory,
    FileModified,
    FileCreated,
    FileFormat,
    Count,
    AlternateSeries,
    AlternateNumber,
    Month,
    Day,
    ScanInformation,
    BookmarkCount,
}
