; Inno Setup script for Paperbunkr (P7, docs/alpha-todo.md).
;
; Packaging approach follows ComicRackCE's own precedent (_reference/ComicRackCE/Installer.iss),
; but with deliberate deviations, decided with the user before writing this file (or added in the
; 2026-09-01 full-customization pass, noted per section below):
;   1. Self-contained publish (dotnet publish -r win-x64 --self-contained) instead of CE's
;      detect-and-download-.NET-Framework-4.8 dance - Paperbunkr bundles its own .NET 8 runtime,
;      so there is no prerequisite-installation [Code] section here at all.
;   2. File-association registration is opt-in via the "associate" [Tasks] entry below, and even
;      then the installer does NOT hand-write the ProgID/extension registry keys itself the way
;      CE's does. It shells out to Paperbunkr.App.exe --register-file-associations, which runs
;      FileAssociationService - the exact same live registry-write path Preferences > Advanced
;      uses - so there is only ever one place that knows the current extension list and one owner
;      of those registry keys, not two systems racing to own them.
;   3. No .NET-Framework/VC++-redist [Code] section (see #1) - what CE's [Code] section is spent
;      on here instead is an opt-in "delete my library data" prompt on uninstall.
;
; Build with installer\BuildInstaller.ps1, which runs the publish step (and generates
; publish\WhatsNew.txt from CHANGELOG.md, see InfoBeforeFile below) then invokes this script - see
; that file for the expected /DMyAppVersion and /DMyAppSetupFile parameters.

#define MyAppName "Paperbunkr"
#ifndef MyAppVersion
#define MyAppVersion "0.1.0-alpha"
#endif
#ifndef MyAppSetupFile
#define MyAppSetupFile "PaperbunkrSetup"
#endif
#define MyAppPublisher "Paperbunkr Project"
#define MyAppExeName "Paperbunkr.App.exe"
#define MyAppURL "https://github.com/heisehis/PaperBunkr"
#define PublishDir "publish\win-x64"

[Setup]
; Generated once for this project - do not reuse for any other installer, and do not regenerate
; on future builds (that would make Windows treat every release as a different, unrelated app for
; upgrade/uninstall purposes).
AppId={{E6F64297-BD9E-4341-A156-5C65C2E6C1DB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}/issues
AppUpdatesURL={#MyAppURL}/releases
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Per-machine install (Program Files, admin/UAC required) - matches CE's own PrivilegesRequired,
; chosen over a per-user install even though Paperbunkr's own file-association writes don't need
; elevation (see the file-header note above).
PrivilegesRequired=admin
OutputDir=Output
OutputBaseFilename={#MyAppSetupFile}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Real bug, found via manual testing: Inno Setup 6 defaults DisableWelcomePage to "yes" (skips
; straight to Select Components) - without this, the whole WelcomeLabel1/WelcomeLabel2 personality
; text below never actually gets shown to anyone.
DisableWelcomePage=no
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
SetupIconFile=..\src\Paperbunkr.App\Assets\paperbunkr.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName={#MyAppName}
; Wizard branding (Welcome/Finished page side image + the small badge on every other page) -
; composited from the app's own logo, per user direction to give the alpha installer some
; personality rather than shipping Inno Setup's stock gray-gradient default.
WizardImageFile=Assets\WizardImage.bmp
WizardSmallImageFile=Assets\WizardSmallImage.bmp
; Pre-install "what's new" page - generated by BuildInstaller.ps1 from CHANGELOG.md's latest entry
; (plain text, not the raw markdown - Inno's info-file viewer has no markdown rendering, so showing
; CHANGELOG.md directly would put literal "##"/"-" characters in front of the user). Falls back to a
; one-line placeholder if run outside BuildInstaller.ps1 (e.g. a bare ISCC invocation), so this key
; never points at a missing file.
InfoBeforeFile=publish\WhatsNew.txt
; NetSparkle-driven auto-update (src/Paperbunkr.App/Services/UpdateService.cs) runs this same
; installer over a copy of Paperbunkr that may still be mid-shutdown when Setup starts (NetSparkle
; exits the app and launches Setup, but doesn't wait for the OS to release file locks). Restart
; Manager integration below detects the app still holding {app}'s files open and closes it, instead
; of failing the file copy - the [Run] "launch after install" entry on the Finished page handles
; getting it running again, so RestartApplications is off to avoid a double-launch.
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
; Custom Welcome-page copy (user direction: "give the installer personality") - Inno Setup's
; %n is a literal line break within a [Messages] string, not a placeholder needing escaping.
WelcomeLabel1=Welcome to the {#MyAppName} Alpha!
WelcomeLabel2=Get ready to get bunked!%n%nYou're about to install {#MyAppName} {#MyAppVersion} on this computer.%n%nA few things before you dive in:%n     -  This is an early alpha - expect rough edges and the occasional bug.%n     -  A ComicRack-inspired comic && manga library and reader, built fresh from scratch.%n     -  Fully self-contained - no separate .NET install needed.%n     -  Your library and settings stay local; nothing leaves this machine.%n     -  Found something broken? We'd love to hear about it.%n%nClick Next to continue, or Cancel to make a quiet escape.
; Custom Finished-page copy, matching the Welcome page's personality (user direction, same as above).
FinishedLabel={#MyAppName} has been tucked into place on this computer.%n%nClick Finish to close this wizard.

[Types]
Name: "full";    Description: "Full installation";
Name: "compact"; Description: "Compact installation";
Name: "custom";  Description: "Custom installation"; Flags: iscustom

[Components]
Name: "app";        Description: "{#MyAppName} (Required)";   Types: full compact custom; Flags: fixed
Name: "start_menu"; Description: "Start Menu shortcut";        Types: full compact
Name: "desktop";     Description: "Desktop shortcut";           Types: full

[Tasks]
; Both off by default (Flags: unchecked) - neither is needed to use Paperbunkr, and file
; associations in particular are deliberately opt-in (see the file-header note on deviation #2):
; Preferences > Advanced offers the same toggle per-format, post-install, for anyone who skips this.
Name: "launchatstartup"; Description: "Launch {#MyAppName} when Windows starts"; GroupDescription: "Additional options:"; Flags: unchecked
Name: "associate";       Description: "Associate comic and manga archive files (.cbz, .cbr, .cb7, and others) with {#MyAppName}"; GroupDescription: "Additional options:"; Flags: unchecked

[Files]
; The entire self-contained publish output (see installer\BuildInstaller.ps1) - exe, every
; managed dll, and the native dependencies (7z.dll under x64\, pdfium.dll, LibHeifSharp.dll, the
; SQLite provider, etc.) all land flat/nested exactly as dotnet publish produced them, so this one
; recursive copy is enough; nothing here is hand-maintained per-file the way CE's list is.
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: app

[Registry]
; "App Paths" only - lets the Windows Run dialog and shell resolve the exe by name. Deliberately
; NOT registering any file-extension ProgID here; see the file-header note above for why.
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\App Paths\{#MyAppExeName}"; ValueType: string; Flags: uninsdeletevalue; ValueData: "{app}\{#MyAppExeName}"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}";                Components: start_menu
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}";     Components: start_menu
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"; Components: start_menu
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}";          Components: desktop
; Per-machine install (PrivilegesRequired=admin above), so this goes to the common (All Users)
; Startup folder rather than {userstartup} - matches every other per-machine artifact here
; (Program Files, HKLM App Paths) instead of tying the shortcut to whichever account ran Setup.
Name: "{commonstartup}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Flags: runminimized; Tasks: launchatstartup

[Run]
; Runs before the "launch program" entry below, and hidden - this is a headless CLI invocation
; (Program.cs intercepts --register-file-associations before Avalonia ever starts a window), not a
; second copy of the app. See the file-header note on deviation #2 for why this shells out instead
; of the installer writing the registry keys itself.
Filename: "{app}\{#MyAppExeName}"; Parameters: "--register-file-associations"; Tasks: associate; Flags: runhidden waituntilterminated; StatusMsg: "Registering file associations..."
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Mirror of the [Run] entry above, run before files are removed (Inno's UninstallRun ordering) so
; the exe still exists to call. Tasks: associate means this only runs for installs that actually
; opted in - Inno remembers the original task selection across the uninstall, no [Code] needed.
Filename: "{app}\{#MyAppExeName}"; Parameters: "--unregister-file-associations"; Tasks: associate; Flags: runhidden waituntilterminated skipifdoesntexist; RunOnceId: "UnregisterFileAssociations"

[Code]
// Opt-in "delete my library data" prompt on uninstall (deviation #3 in the file header). Paperbunkr
// itself never writes anything outside %APPDATA%\Paperbunkr (see
// src/Paperbunkr.Data/PaperbunkrDbContext.cs's own DbPath resolution, which this path matches
// exactly) - the user's actual comic/book files on disk are never touched either way, only
// Paperbunkr's own library index/settings/cache. Guarded by "not UninstallSilent" so a silent
// uninstall (e.g. driven by another installer or a scripted CI cleanup) never blocks on a prompt
// nobody can see.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
begin
  if CurUninstallStep = usUninstall then
  begin
    if not UninstallSilent then
    begin
      DataDir := ExpandConstant('{userappdata}\Paperbunkr');
      if DirExists(DataDir) then
      begin
        if MsgBox('Also delete your Paperbunkr library data (database, settings, and cached thumbnails)?' + #13#10 + #13#10 + DataDir + #13#10 + #13#10 + 'Your comic and book files themselves are never touched - only Paperbunkr''s own library index.', mbConfirmation, MB_YESNO) = IDYES then
          DelTree(DataDir, True, True, True);
      end;
    end;
  end;
end;
